Repository lzim/mtl, pull requests merged in 2021-05, with the labels that each got.

#214 Feature gh pages screenshot fix
  02_introduction.md
  index.Rmd
Labels: facilitate

#215 Update 02_introduction.md
  02_introduction.md
Labels: facilitate

#218 Feature gh pages checklists
  04_mtl_blue_facilitator_session_04_say.md
  04_mtl_blue_facilitator_session_05_say.md
  04_mtl_blue_facilitator_session_06_say.md
  04_mtl_blue_facilitator_session_07_say.md
  04_mtl_blue_facilitator_session_08_say.md
  04_mtl_blue_facilitator_session_09_say.md
  04_mtl_blue_facilitator_session_10_say.md
  04_mtl_blue_facilitator_session_11_say.md
  04_mtl_blue_facilitator_session_12_say.md
  04_mtl_blue_learner_session_01_see.md
  04_mtl_blue_learner_session_02_see.md
  04_mtl_blue_learner_session_03_see.md
  04_mtl_blue_learner_session_04_see.md
  04_mtl_blue_learner_session_05_see.md
  04_mtl_blue_learner_session_06_see.md
  04_mtl_blue_learner_session_07_see.md
  04_mtl_blue_learner_session_08_see.md
  04_mtl_blue_learner_session_09_see.md
  04_mtl_blue_learner_session_10_see.md
  04_mtl_blue_learner_session_11_see.md
  04_mtl_blue_learner_session_12_see.md
  _bookdown.yml
  apply_fidelity_checklist.md
  build_fidelity_checklist.md
  facilitator_checklists.md
  intersession_fidelity_training_checklist.md
  mtl_blue_session_01_say_checklist.md
  mtl_blue_session_02_say_checklist.md
  mtl_blue_session_03_say_checklist.md
  mtl_blue_session_04_say_checklist.md
  mtl_blue_session_05_say_checklist.md
  mtl_blue_session_06_say_checklist.md
  mtl_blue_session_07_say_checklist.md
  mtl_blue_session_08_say_checklist.md
  mtl_blue_session_09_say_checklist.md
  mtl_blue_session_10_say_checklist.md
  mtl_blue_session_11_say_checklist.md
  mtl_blue_session_12_say_checklist.md
  partner_fidelity_checklist.md
  post_session_checklist.md
  pre_session_checklist.md
  session_debrief_examples.md
Labels: hq

#219 Update _bookdown.yml
  _bookdown.yml
Labels: hq

#220 Update renderbook.yml
  .github/workflows/renderbook.yml
Labels: hq

#221 Feature gh pages file size error
  .github/workflows/renderbook.yml
  _bookdown.yml
Labels: hq

#223 Feature gh pages file size error
  .github/workflows/renderbook.yml
  04_mtl_blue_facilitator_session_04_say.md
  04_mtl_blue_facilitator_session_05_say.md
  04_mtl_blue_facilitator_session_06_say.md
  04_mtl_blue_facilitator_session_07_say.md
  04_mtl_blue_facilitator_session_08_say.md
  04_mtl_blue_facilitator_session_09_say.md
  04_mtl_blue_facilitator_session_10_say.md
  04_mtl_blue_facilitator_session_11_say.md
  04_mtl_blue_facilitator_session_12_say.md
  build_fidelity_checklist.md
  mtl_blue_session_02_say_checklist.md
Labels: hq

#224 Update renderbook.yml
  .github/workflows/renderbook.yml
Labels: hq

#225 Update renderbook.yml
  .github/workflows/renderbook.yml
Labels: hq

#227 Feature gh pages facilitator dashboard
  _bookdown.yml
  facilitate_cheatsheet.pdf
  faciltator_dashboard.md
  images/select tt admin.png
  images/select_charts.png
  images/select_team_module.png
  mtl_blue_session_01_say_checklist.md
  mtl_blue_session_02_say_checklist.md
  mtl_blue_session_03_say_checklist.md
  mtl_blue_session_04_say_checklist.md
  mtl_blue_session_07_say_checklist.md
  mtl_blue_session_08_say_checklist.md
  mtl_blue_session_09_say_checklist.md
  mtl_blue_session_10_say_checklist.md
  mtl_technical_manual.md
  mtl_technical_manual_admin.md
  mtl_technical_manual_facilitator.md
Labels: hq

#228 Feature gh pages facilitator dashboard
  faciltator_dashboard.md
Labels: hq

#229 Feature gh pages facilitator dashboard
  faciltator_dashboard.md
Labels: hq

#231 Feature gh pages facilitator one pager
  _bookdown.yml
  facilitator_one_pager.md
  faciltator_dashboard.md
  images/add_ind.png
  images/enter_ind_alias.png
  images/nav_to_team_setup.png
  images/select_charts.png
  images/select_ind_team.png
  images/select_team_module.png
Labels: hq

#230 Feature gh pages facilitator dashboard
  _bookdown.yml
  facilitator_one_pager.md
  faciltator_dashboard.md
  images/add_ind.png
  images/enter_ind_alias.png
  images/nav_to_team_setup.png
  images/select_charts.png
  images/select_ind_team.png
  images/select_team_module.png
Labels: hq, sim_ui

#232 Update faciltator_dashboard.md
  faciltator_dashboard.md
Labels: hq
