Repository lzim/mtl, pull requests merged in 2021-12, with the labels that each got.

#289 Feature pbi update - Session 2 Documentation
  blue/session01/s01_learner/mtl_session01_see.md
  blue/session02/s02_facilitator/mtl_session02_say.md
  blue/session02/s02_facilitator/mtl_session02_say_checklist.md
  blue/session02/s02_learner/mtl_session02_see.md
  blue/session03/s03_learner/mtl_session03_see.md
Labels: facilitate, quant

#290 QA Session 2 Guide Edits into Master
  blue/session01/s01_learner/mtl_session01_see.md
  blue/session02/s02_facilitator/mtl_how_2.5_data_cheatsheet.pdf
  blue/session02/s02_facilitator/mtl_how_data_facilitator_one_pager.pdf
  blue/session02/s02_facilitator/mtl_session02_say.md
  blue/session02/s02_facilitator/mtl_session02_say_checklist.md
  blue/session02/s02_learner/mtl_how_2.5_data_cheatsheet.pdf
  blue/session02/s02_learner/mtl_how_data_cheatsheet.pdf
  blue/session02/s02_learner/mtl_session02_see.md
  blue/session03/s03_facilitator/mtl_how_data_facilitator_one_pager.pdf
  blue/session03/s03_learner/mtl_how_data_cheatsheet.pdf
  blue/session03/s03_learner/mtl_session03_see.md
  red/part1/part1_facilitator/mtl_how_data_facilitator_one_pager.pdf
  red/part1/part1_facilitator/va_part_1_say_data.md
  red/part1/part1_facilitator/va_part_1_say_viz.md
  red/part1/part1_learner/mtl_how_data_cheatsheet.pdf
  red/part2/part2_facilitator/mtl_how_data_facilitator_one_pager.pdf
  red/part2/part2_facilitator/va_part_2_say_params.md
  red/part2/part2_learner/mtl_how_data_cheatsheet.pdf
Labels: hq

#291 Update MTL Data Cheatsheet
  blue/session02/s02_facilitator/mtl_how_2.5_data_cheatsheet.pdf
  blue/session02/s02_learner/mtl_how_2.5_data_cheatsheet.pdf
Labels: hq

#294 QA to Master
  red/part1/part1_facilitator/mtl_red_part_1_say_checklist.md
  red/part1/part1_facilitator/va_part_1_say_viz.md
  red/part1/part1_facilitator/va_part_1_say_viz_checklist.md
Labels: hq

#295 MTL Blue Session 2 Guides Additional Edits
  blue/session02/s02_facilitator/mtl_session02_say.md
  blue/session02/s02_facilitator/mtl_session02_say_checklist.md
  blue/session02/s02_learner/mtl_session02_see.md
  red/part1/part1_facilitator/mtl_red_part_1_say.md
  red/part1/part1_facilitator/mtl_red_part_1_say_checklist.md
  red/part1/part1_facilitator/va_part_1_say_data.md
  red/part1/part1_facilitator/va_part_1_say_viz.md
  red/part1/part1_facilitator/va_part_1_say_viz_checklist.md
  red/part1/part1_learner/mtl_red_part_1_see.md
Labels: facilitate

#296 Qa into Master
  blue/session02/s02_facilitator/mtl_session02_say.md
  blue/session02/s02_facilitator/mtl_session02_say_checklist.md
  blue/session02/s02_learner/mtl_session02_see.md
  red/part1/part1_facilitator/mtl_red_part_1_say.md
  red/part1/part1_facilitator/mtl_red_part_1_say_checklist.md
  red/part1/part1_facilitator/va_part_1_say_data.md
  red/part1/part1_facilitator/va_part_1_say_viz.md
  red/part1/part1_facilitator/va_part_1_say_viz_checklist.md
  red/part1/part1_learner/mtl_red_part_1_see.md
Labels: facilitate

#297 Feature pbi blue s3 update
  blue/session02/s02_facilitator/mtl_how_data_2.5_facilitator_one_pager.pdf
  blue/session02/s02_learner/mtl_session02_see.md
  blue/session03/s03_facilitator/mtl_session03_say.md
  blue/session03/s03_facilitator/mtl_session03_say_checklist.md
  blue/session03/s03_learner/mtl_session03_see.md
  red/part1/part1_facilitator/mtl_how_data_2.5_facilitator_one_pager.pdf
  red/part1/part1_facilitator/mtl_red_part_1_say.md
  red/part1/part1_learner/mtl_red_part_1_see.md
Labels: facilitate

#298 Qa to Master
  blue/session02/s02_learner/mtl_session02_see.md
  blue/session03/s03_facilitator/mtl_session03_say.md
  blue/session03/s03_facilitator/mtl_session03_say_checklist.md
  blue/session03/s03_learner/mtl_session03_see.md
Labels: facilitate
