Repository lzim/mtl, pull requests merged in 2021-09, with the labels that each got.

#260 Remove facility detail
  blue/session02/s02_facilitator/mtl_session02_say.md
  blue/session02/s02_facilitator/mtl_session02_say_checklist.md
  blue/session02/s02_learner/mtl_session02_see.md
  red/part1/part1_facilitator/mtl_red_part_1_say.md
  red/part1/part1_learner/mtl_red_part_1_see.md
Labels: hq, facilitate

#264 update_readme_remove_adobe_connect
  readme.md
Labels: facilitate

#272 Update data cheatsheet
  blue/session02/s02_learner/mtl_how_data_cheatsheet.pdf
  blue/session03/s03_learner/mtl_how_data_cheatsheet.pdf
  blue/session04/s04_learner/mtl_how_data_cheatsheet.pdf
  red/part1/part1_learner/mtl_how_data_cheatsheet.pdf
  red/part2/part2_learner/mtl_how_data_cheatsheet.pdf
Labels: facilitate, quant
