Repository lzim/mtl, pull requests merged in 2022-05, with the labels that each got.

#354 Feature readme mtl blue
  blue/session11/s11_facilitator/README.md
  blue/session11/s11_facilitator/mtl_session11_say.md
  blue/session11/s11_facilitator/mtl_session11_say_checklist.md
  blue/session11/s11_learner/mtl_session11_see.md
  blue/session12/README.md
  blue/session12/s12_facilitator/README.md
  blue/session12/s12_facilitator/mtl_session12_say.md
  blue/session12/s12_facilitator/mtl_session12_say_checklist.md
  blue/session12/s12_learner/mtl_how_3.0_data_cheatsheet.pdf
  blue/session12/s12_learner/mtl_session12_see.md
  blue/session12/s12_resources/README.md
Labels: hq, facilitate, Operations

#355 Update Master with QA
  blue/session11/s11_facilitator/README.md
  blue/session11/s11_facilitator/mtl_session11_say.md
  blue/session11/s11_facilitator/mtl_session11_say_checklist.md
  blue/session11/s11_learner/mtl_session11_see.md
  blue/session12/README.md
  blue/session12/s12_facilitator/README.md
  blue/session12/s12_facilitator/mtl_session12_say.md
  blue/session12/s12_facilitator/mtl_session12_say_checklist.md
  blue/session12/s12_learner/mtl_how_3.0_data_cheatsheet.pdf
  blue/session12/s12_learner/mtl_session12_see.md
  blue/session12/s12_resources/README.md
Labels: hq, facilitate, Operations

#356 Qa blue_session guides updates sessions 5-8
  blue/session03/s03_facilitator/mtl_session03_say.md
  blue/session04/s04_facilitator/mtl_session04_say.md
  blue/session04/s04_facilitator/mtl_session04_say_checklist.md
  blue/session04/s04_learner/mtl_session04_see.md
  blue/session05/s05_learner/mtl_session05_see.md
  blue/session06/s06_learner/mtl_session06_see.md
  blue/session07/s07_learner/mtl_session07_see.md
  blue/session08/s08_learner/mtl_session08_see.md
  blue/session09/s09_learner/mtl_session09_see.md
  release_1.7/mtl_session04_see.md
Labels: Development, Operations

#358 Feature qa s5 s8
  blue/session05/README.md
  blue/session05/s05_facilitator/README.md
  blue/session05/s05_facilitator/mtl_session05_say.md
  blue/session05/s05_facilitator/mtl_session05_say_checklist.md
  blue/session05/s05_learner/mtl_session05_see.md
  blue/session06/README.md
  blue/session06/s06_facilitator/README.md
  blue/session06/s06_facilitator/mtl_session06_say.md
  blue/session06/s06_facilitator/mtl_session06_say_checklist.md
  blue/session06/s06_learner/mtl_session06_see.md
  blue/session07/README.md
  blue/session07/s07_facilitator/README.md
  blue/session07/s07_facilitator/mtl_session07_say.md
  blue/session07/s07_facilitator/mtl_session07_say_checklist.md
  blue/session07/s07_learner/mtl_session07_see.md
  blue/session08/README.md
  blue/session08/s08_facilitator/README.md
  blue/session08/s08_facilitator/mtl_session08_say.md
  blue/session08/s08_facilitator/mtl_session08_say_checklist.md
  blue/session08/s08_learner/mtl_session08_see.md
Labels: facilitate, Operations

#359 Sync QA to Master
  blue/session05/README.md
  blue/session05/s05_facilitator/README.md
  blue/session05/s05_facilitator/mtl_session05_say.md
  blue/session05/s05_facilitator/mtl_session05_say_checklist.md
  blue/session05/s05_learner/mtl_session05_see.md
  blue/session06/README.md
  blue/session06/s06_facilitator/README.md
  blue/session06/s06_facilitator/mtl_session06_say.md
  blue/session06/s06_facilitator/mtl_session06_say_checklist.md
  blue/session06/s06_learner/mtl_session06_see.md
  blue/session07/README.md
  blue/session07/s07_facilitator/README.md
  blue/session07/s07_facilitator/mtl_session07_say.md
  blue/session07/s07_facilitator/mtl_session07_say_checklist.md
  blue/session07/s07_learner/mtl_session07_see.md
  blue/session08/README.md
  blue/session08/s08_facilitator/README.md
  blue/session08/s08_facilitator/mtl_session08_say.md
  blue/session08/s08_facilitator/mtl_session08_say_checklist.md
  blue/session08/s08_learner/mtl_session08_see.md
Labels: facilitate, Development, Operations, Research

#361 QA
  blue/session01/s01_facilitator/partner_fidelity.md
Labels: facilitate, Development, Operations, pi

#362 Create partner_fidelity.md
  blue/session02/s02_facilitator/partner_fidelity.md
Labels: facilitate, Development, Operations

#364 Feature s03 s04 partner fidelity
  blue/session01/s01_facilitator/README.md
  blue/session02/s02_facilitator/README.md
  blue/session03/s03_facilitator/README.md
  blue/session03/s03_facilitator/partner_fidelity.md
  blue/session04/s04_facilitator/README.md
  blue/session04/s04_facilitator/partner_fidelity.md
Labels: facilitate, Development, Operations, pi

#365 QA
  blue/session01/s01_facilitator/README.md
  blue/session02/s02_facilitator/README.md
  blue/session03/s03_facilitator/README.md
  blue/session03/s03_facilitator/partner_fidelity.md
  blue/session04/s04_facilitator/README.md
  blue/session04/s04_facilitator/partner_fidelity.md
Labels: facilitate, Development, Operations, pi

#369 Feature done do fixes
  blue/session02/s02_facilitator/mtl_session02_say.md
  blue/session02/s02_learner/mtl_session02_see.md
Labels: facilitate, Development, Operations, pi

#370 QA
  blue/session02/s02_facilitator/mtl_session02_say.md
  blue/session02/s02_learner/mtl_session02_see.md
Labels: facilitate, Development, Operations, pi

#368 Feature done do fixes
  blue/session02/s02_facilitator/mtl_session02_say.md
  blue/session02/s02_learner/mtl_session02_see.md
Labels: facilitate, Development, Operations, Research, pi

#373 Qa
  blue/session02/s02_facilitator/mtl_session02_say.md
Labels: facilitate, Operations

#380 Update Done/Dos
  blue/session03/s03_facilitator/mtl_session03_say.md
  blue/session03/s03_facilitator/mtl_session03_say_checklist.md
  blue/session03/s03_learner/mtl_session03_see.md
  blue/session04/s04_facilitator/mtl_session04_say.md
  blue/session04/s04_facilitator/mtl_session04_say_checklist.md
  blue/session04/s04_learner/mtl_session04_see.md
  red/part2/part2_facilitator/mtl_red_part_2_say.md
  red/part2/part2_facilitator/mtl_red_part_2_say_checklist.md
  red/part2/part2_learner/mtl_red_part_2_see.md
Labels: facilitate, Operations
