Repository lzim/mtl, pull requests merged in 2022-04, with the labels that each got.

#342 Update QA with Master
  red/part1/part1_facilitator/mtl_red_part_1_say.md
  red/part1/part1_facilitator/mtl_red_part_1_say_checklist.md
  red/part1/part1_learner/mtl_red_part_1_see.md
Labels: hq, facilitate

#343 Update faciltator_dashboard.md
  faciltator_dashboard.md
Labels: hq

#344 Qa
  blue/session03/s03_facilitator/mtl_session03_say.md
  blue/session03/s03_facilitator/mtl_session03_say_checklist.md
Labels: facilitate

#347 Qa
  blue/session01/s01_facilitator/mtl_session01_say.md
  blue/session04/s04_facilitator/mtl_session04_say.md
  blue/session04/s04_facilitator/mtl_session04_say_checklist.md
  blue/session12/s12_facilitator/mtl_session12_say.md
  blue/session12/s12_facilitator/mtl_session12_say_checklist.md
  blue/session12/s12_learner/mtl_session12_see.md
  release_1.7/mtl_session12_see.md
Labels: facilitate, Operations

#351 Feature add intro heading session2
  blue/session02/s02_facilitator/mtl_session02_say.md
  blue/session02/s02_facilitator/mtl_session02_say_checklist.md
  red/part1/part1_facilitator/mtl_red_part_1_say.md
  red/part1/part1_facilitator/mtl_red_part_1_say_checklist.md
  red/part1/part1_learner/mtl_red_part_1_see.md
Labels: hq, Operations

#352 Sync QA with Master
  blue/session01/README.md
  blue/session01/s01_facilitator/README.md
  blue/session01/s01_facilitator/mtl_session01_say.md
  blue/session01/s01_facilitator/mtl_session01_say_checklist.md
  blue/session01/s01_learner/README.md
  blue/session01/s01_learner/mtl_session01_see.md
  blue/session02/s02_facilitator/mtl_session02_say.md
  blue/session02/s02_facilitator/mtl_session02_say_checklist.md
  red/part1/part1_facilitator/mtl_red_part_1_say.md
  red/part1/part1_facilitator/mtl_red_part_1_say_checklist.md
  red/part1/part1_learner/mtl_red_part_1_see.md
Labels: hq, Operations
