Repository lzim/mtl, pull requests merged in 2022-06, with the labels that each got.

#381 Update mtl_session01_say.md
  blue/session01/s01_facilitator/mtl_session01_say.md
Labels: facilitate, Operations

#382 Sync QA with Master
  blue/session03/s03_facilitator/mtl_session03_say.md
  blue/session03/s03_facilitator/mtl_session03_say_checklist.md
  blue/session03/s03_learner/mtl_session03_see.md
  blue/session04/s04_facilitator/mtl_session04_say.md
  blue/session04/s04_facilitator/mtl_session04_say_checklist.md
  blue/session04/s04_learner/mtl_session04_see.md
  red/part2/part2_facilitator/mtl_red_part_2_say.md
  red/part2/part2_facilitator/mtl_red_part_2_say_checklist.md
  red/part2/part2_learner/mtl_red_part_2_see.md
Labels: facilitate, Operations

#383 Qa to Master to incorporate Swaps S01 Edits
  blue/session01/s01_facilitator/mtl_session01_say.md
Labels: facilitate, Operations

#385 Sync QA with Master
  blue/session01/s01_facilitator/mtl_how_3.0_facilitator_cross_platform_cheatsheet.pdf
Labels: Operations

#371 _MTL_ 3.0 model folder
  blue/mtl2.0_models/agg_i_v15_2021_07_13-A.html
  blue/mtl2.0_models/agg_i_v15_2021_07_13.mdl
  blue/mtl2.0_models/agg_i_v15_2021_07_13.vmfx
  blue/mtl3.0_models/ModelParameters.xlsx
  blue/mtl3.0_models/README.md
  blue/mtl3.0_models/agg_i_v15_2022_01_10.1-A.html
  blue/mtl3.0_models/agg_i_v15_2022_01_10.1.mdl
  blue/mtl3.0_models/agg_i_v15_2022_01_10.1.vmfx
  blue/mtl3.0_models/agg_i_v15_2022_01_10.1.xmile
  blue/mtl3.0_models/cc_i_v36_2022_01_10.1-A.html
  blue/mtl3.0_models/cc_i_v36_2022_01_10.1.mdl
  blue/mtl3.0_models/cc_i_v36_2022_01_10.1.vmfx
  blue/mtl3.0_models/cc_i_v36_2022_01_10.1.xmile
  blue/mtl3.0_models/mm_i_v36_2022_01_11.1-A.html
  blue/mtl3.0_models/mm_i_v36_2022_01_11.1.mdl
  blue/mtl3.0_models/mm_i_v36_2022_01_11.1.vmfx
  blue/mtl3.0_models/mm_i_v36_2022_01_11.1.xmile
  blue/mtl3.0_models/psy_i_v21_2022_02_11.1-A.html
  blue/mtl3.0_models/psy_i_v21_2022_02_11.1.mdl
  blue/mtl3.0_models/psy_i_v21_2022_02_11.1.vmfx
  blue/mtl3.0_models/psy_i_v21_2022_02_11.1.xmile
  blue/mtl3.0_models/sp_i_v4_2022_02_16-A.html
  blue/mtl3.0_models/sp_i_v4_2022_02_17-A.html
  blue/mtl3.0_models/sp_i_v4_2022_02_17.mdl
  blue/mtl3.0_models/sp_i_v4_2022_02_17.vmfx
  blue/mtl3.0_models/sp_i_v4_2022_02_17.xmile
Labels: model

#392 Sync QA with Master
  blue/session05/s05_facilitator/mtl_session05_say.md
Labels: Operations

#393 Merge QA to Master
  blue/session01/s01_facilitator/mtl_blue_post_session01.md
  blue/session01/s01_facilitator/mtl_blue_pre_session01.md
  blue/session02/s02_facilitator/mtl_blue_post_session02.md
  blue/session02/s02_facilitator/mtl_blue_pre_session02.md
  blue/session02/s02_facilitator/mtl_how_3.0_data_facilitator_one_pager.pdf
  blue/session03/s03_facilitator/mtl_blue_post_session03.md
  blue/session03/s03_facilitator/mtl_blue_pre_session03.md
  blue/session03/s03_facilitator/mtl_how_3.0_data_facilitator_one_pager.pdf
  blue/session04/s04_facilitator/mtl_blue_post_session04.md
  blue/session04/s04_facilitator/mtl_blue_pre_session04.md
  blue/session05/s05_facilitator/mtl_blue_post_session05.md
  blue/session05/s05_facilitator/mtl_blue_pre_session05.md
  blue/session06/s06_facilitator/mtl_blue_post_session06.md
  blue/session06/s06_facilitator/mtl_blue_pre_session06.md
  blue/session07/s07_facilitator/mtl_blue_post_session07.md
  blue/session07/s07_facilitator/mtl_blue_pre_session07.md
  blue/session08/s08_facilitator/mtl_blue_post_session08.md
  blue/session08/s08_facilitator/mtl_blue_pre_session08.md
  blue/session09/s09_facilitator/mtl_blue_post_session09.md
  blue/session09/s09_facilitator/mtl_blue_pre_session09.md
  blue/session10/s10_facilitator/mtl_blue_post_session10.md
  blue/session10/s10_facilitator/mtl_blue_pre_session10.md
  blue/session11/s11_facilitator/mtl_blue_post_session11.md
  blue/session11/s11_facilitator/mtl_blue_pre_session11.md
  blue/session12/s12_facilitator/mtl_blue_post_session12.md
  blue/session12/s12_facilitator/mtl_blue_pre_session12.md
  red/part1/part1_facilitator/mtl_how_3.0_data_facilitator_one_pager.pdf
  red/part1/part1_facilitator/mtl_red_post_part_1.md
  red/part1/part1_facilitator/mtl_red_pre_part_1.md
  red/part1/part1_facilitator/mtl_red_session_1_to_6_pre_post/mtl_red_pre_session_01.md
  red/part1/part1_facilitator/mtl_red_session_1_to_6_pre_post/mtl_red_pre_session_02.md
  red/part1/part1_facilitator/mtl_red_session_1_to_6_pre_post/mtl_red_pre_session_03.md
  red/part1/part1_facilitator/mtl_red_session_1_to_6_pre_post/mtl_red_pre_session_04.md
  red/part1/part1_facilitator/mtl_red_session_1_to_6_pre_post/mtl_red_pre_session_05.md
  red/part1/part1_facilitator/mtl_red_session_1_to_6_pre_post/mtl_red_pre_session_06.md
  red/part1/part1_facilitator/mtl_red_session_1_to_6_pre_post/mtl_red_pre_session_07.md
  red/part1/part1_facilitator/mtl_red_session_1_to_6_pre_post/mtl_red_pre_session_08.md
  red/part1/part1_facilitator/mtl_red_session_1_to_6_pre_post/mtl_red_pre_session_09.md
  red/part1/part1_facilitator/mtl_red_session_1_to_6_pre_post/mtl_red_pre_session_10.md
  red/part1/part1_facilitator/mtl_red_session_1_to_6_pre_post/mtl_red_pre_session_11.md
  red/part1/part1_facilitator/mtl_red_session_1_to_6_pre_post/mtl_red_pre_session_12.md copy
  red/part2/part2_facilitator/mtl_how_3.0_data_facilitator_one_pager.pdf
  red/part2/part2_facilitator/mtl_red_post_part_2.md
  red/part2/part2_facilitator/mtl_red_pre_part_2.md
  red/part2/part2_facilitator/mtl_red_session_7_to_12_pre_post/mtl_red_post_session_01.md
  red/part2/part2_facilitator/mtl_red_session_7_to_12_pre_post/mtl_red_post_session_02.md
  red/part2/part2_facilitator/mtl_red_session_7_to_12_pre_post/mtl_red_post_session_03.md
  red/part2/part2_facilitator/mtl_red_session_7_to_12_pre_post/mtl_red_post_session_04.md
  red/part2/part2_facilitator/mtl_red_session_7_to_12_pre_post/mtl_red_post_session_05.md
  red/part2/part2_facilitator/mtl_red_session_7_to_12_pre_post/mtl_red_post_session_06.md
  red/part2/part2_facilitator/mtl_red_session_7_to_12_pre_post/mtl_red_post_session_07.md
  red/part2/part2_facilitator/mtl_red_session_7_to_12_pre_post/mtl_red_post_session_08.md
  red/part2/part2_facilitator/mtl_red_session_7_to_12_pre_post/mtl_red_post_session_09.md
  red/part2/part2_facilitator/mtl_red_session_7_to_12_pre_post/mtl_red_post_session_10.md
  red/part2/part2_facilitator/mtl_red_session_7_to_12_pre_post/mtl_red_post_session_11.md
  red/part2/part2_facilitator/mtl_red_session_7_to_12_pre_post/mtl_red_post_session_12.md
Labels: Operations

#395 Add files via upload
  red/part1/part1_facilitator/mtl_how_3.0_facilitator_pre_session_post.md.pdf
Labels: Development
